### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by olegsvs** [HostZero/android_device_coolpad_CP8298_I00#1]
This full forked device tree? patches?

**Comment by HostZero** [comment]
Yes!, I have cloned your benefit m7 device tree and pusht to branch cm-13.0 and started modification. I hope you will help us out in this project, I will start the builds from next week.

**Comment by olegsvs** [comment]
Ok, me not can bringup RIL on my builds https://github.com/olegsvs/android_device_ark_benefit_m7/tree/cm-13.0_32 In the near future I will continue to work , in port aicp11 from your device ril and mobile data work!

**Comment by HostZero** [comment]
Actually I am practically not sure, if my RIL is also fine where as I am using the proprietary list from https://github.com/visi0nary/android_device_elephone_p8000/blob/cm-12.1/proprietary-files.txt

Where as I will go through, fire855 and ferhung device tree for RIL or I will checkup in stock ROM.
